name: space_x
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.5.4
  flutter_riverpod: ^2.0.2
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  flutter_gen_runner: ^5.1.0+1
  modal_bottom_sheet: ^2.1.2
  smooth_page_indicator: ^1.0.0+2
  isar: ^3.0.4
  isar_flutter_libs: ^3.0.4
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.1
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  retrofit_generator: ^4.2.0
  isar_generator: ^3.0.4

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  fonts:
    enabled: false

flutter:
  uses-material-design: false
  assets:
    - assets/images/
  fonts:
    - family: LabGrotesque
      fonts:
        - asset: assets/fonts/LabGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/LabGrotesque-Bold.ttf
          weight: 700